// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    Button: typeof import('./src/components/atoms/Button.vue')['default']
    Input: typeof import('./src/components/atoms/Input.vue')['default']
    Textarea: typeof import('./src/components/atoms/Textarea.vue')['default']
    Container: typeof import('./src/components/bosons/Container.vue')['default']
    FormCard: typeof import('./src/components/molecules/FormCard.vue')['default']
  }
}

export { }
